name = "ken/baby-play"

version = "1.1.0"

description = """How to entertain a baby based on their age in weeks.
Helps you adapt to their ever-changing needs."""

steps = [
    "/ask-human(cache=true) When was your baby born?",
    "/std now",
    "/std new-day-alert",
    """/pin When prompted for activities, list specific activities in a table
with columns for the type of activity, the purpose of the activity, and how
long it can be done for.
    """,
    """/prompt Calculate the number of weeks old my baby is and suggest some
good activities to nurture her development.""",
]
